// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kshvyryaev/cyber-meower-habr-worker/pkg/service"
	"github.com/kshvyryaev/cyber-meower-habr-worker/pkg/worker"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeHabrDownloaderWorker(logger *zap.Logger) (*worker.HabrDownloaderWorker, func()) {
	habrDownloaderService := service.ProvideHabrDownloaderService()
	habrDownloaderWorker, cleanup := worker.ProvideHabrDownloaderWorker(habrDownloaderService, logger)
	return habrDownloaderWorker, func() {
		cleanup()
	}
}

func InitializeHabrUploaderWorker(logger *zap.Logger) *worker.HabrUploaderWorker {
	habrUploaderWorker := worker.ProvideHabrUploaderWorker(logger)
	return habrUploaderWorker
}
