// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kshvyryaev/cyber-meower-habr-worker/pkg"
	"github.com/kshvyryaev/cyber-meower-habr-worker/pkg/client"
	"github.com/kshvyryaev/cyber-meower-habr-worker/pkg/service"
	"github.com/kshvyryaev/cyber-meower-habr-worker/pkg/worker"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeHabrDownloaderWorker(logger *zap.Logger) (*worker.HabrDownloaderWorker, func()) {
	habrDownloaderService := service.ProvideHabrDownloaderService()
	habrDownloaderWorker, cleanup := worker.ProvideHabrDownloaderWorker(habrDownloaderService, logger)
	return habrDownloaderWorker, func() {
		cleanup()
	}
}

func InitializeHabrUploaderWorker(config *pkg.Config, logger *zap.Logger) (*worker.HabrUploaderWorker, func(), error) {
	clientConn, cleanup, err := client.ProvideMeowerServiceGrpcConnection(config)
	if err != nil {
		return nil, nil, err
	}
	grpcMeowClient := client.ProvideGrpcMeowClient(clientConn)
	habrUploaderWorker := worker.ProvideHabrUploaderWorker(grpcMeowClient, logger)
	return habrUploaderWorker, func() {
		cleanup()
	}, nil
}
